name: SonarQube Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        # Menggunakan v4 terbaru agar kompatibel dengan sistem GitHub Node/Cache baru
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0  
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          # Increases timeout to 300 seconds (5 minutes) to survive slow Ngrok tunnels
          SONAR_SCANNER_OPTS: "-Dsonar.ws.timeout=300"
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
